### ISSUE TITLE
Missing function 'computeAreas.m'

### ISSUE THREAD

**Issue by aligurbu** [mickjt/lipid-rupture-cellular-automaton#1]
It seems like you forget to push the 'computeAreas.m' function. If you could provide this function, that would be great. 

https://github.com/mickjt/lipid-rupture-cellular-automaton/blob/e7bcd17f88d75a7d28b891bf5059d6b01c5bfec7/LipidCA_main.m#L64

https://github.com/mickjt/lipid-rupture-cellular-automaton/blob/e7bcd17f88d75a7d28b891bf5059d6b01c5bfec7/LipidCA_main.m#L90

Thanks a lot.

**Comment by mickjt** [comment]
I just added the missing function. Thanks for letting me know!
